//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NETMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURANTS
    {
        public int ID_COURANT { get; set; }
        public Nullable<int> ID_GENRE { get; set; }
        public string LIBELLE_COURANT { get; set; }
    
        public virtual GENRES GENRES { get; set; }
    }
}
