//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NETMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVRES
    {
        public int ID_LIVRE { get; set; }
        public Nullable<decimal> ISBN { get; set; }
        public string TITRE { get; set; }
        public string EDITEUR { get; set; }
        public Nullable<System.DateTime> ANNEE_EDITION { get; set; }
        public Nullable<int> ID_AUTEUR { get; set; }
        public Nullable<int> ID_GENRE { get; set; }
        public string LIVRE { get; set; }
        public string URL_LIVRE { get; set; }
    
        public virtual AUTEURS AUTEURS { get; set; }
        public virtual GENRES GENRES { get; set; }
    }
}
