//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NETMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIBLIOTHEQUEEntities : DbContext
    {
        public BIBLIOTHEQUEEntities()
            : base("name=BIBLIOTHEQUEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTEURS> AUTEURS { get; set; }
        public virtual DbSet<COURANTS> COURANTS { get; set; }
        public virtual DbSet<GENRES> GENRES { get; set; }
        public virtual DbSet<LIVRES> LIVRES { get; set; }
    }
}
